/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive access/refresh tokens */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh token pair */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List parties */
        get: operations["list_parties_parties_get"];
        put?: never;
        /** Create a party */
        post: operations["create_party_parties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a party */
        get: operations["get_party_parties__party_guid__get"];
        put?: never;
        post?: never;
        /** Delete a party */
        delete: operations["delete_party_parties__party_guid__delete"];
        options?: never;
        head?: never;
        /** Update a party */
        patch: operations["update_party_parties__party_guid__patch"];
        trace?: never;
    };
    "/parties/{party_guid}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List party contacts */
        get: operations["list_contacts_parties__party_guid__contacts_get"];
        put?: never;
        /** Create party contact */
        post: operations["create_contact_parties__party_guid__contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{contact_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete contact */
        delete: operations["delete_contact_contacts__contact_guid__delete"];
        options?: never;
        head?: never;
        /** Update contact */
        patch: operations["update_contact_contacts__contact_guid__patch"];
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create location */
        post: operations["create_location_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{location_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get location */
        get: operations["get_location_locations__location_guid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party_guid}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List party locations */
        get: operations["list_party_locations_parties__party_guid__locations_get"];
        put?: never;
        /** Create party location */
        post: operations["create_party_location_parties__party_guid__locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/party-locations/{party_location_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete party location */
        delete: operations["delete_party_location_party_locations__party_location_guid__delete"];
        options?: never;
        head?: never;
        /** Update party location */
        patch: operations["update_party_location_party_locations__party_location_guid__patch"];
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List articles */
        get: operations["list_articles_articles_get"];
        put?: never;
        /** Create article */
        post: operations["create_article_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_guid}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List article aliases */
        get: operations["list_aliases_articles__article_guid__aliases_get"];
        put?: never;
        /** Create article alias */
        post: operations["add_alias_articles__article_guid__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List warehouses */
        get: operations["list_warehouses_warehouses_get"];
        put?: never;
        /** Create warehouse */
        post: operations["create_warehouse_warehouses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders */
        get: operations["list_orders_orders_get"];
        put?: never;
        /** Create order */
        post: operations["create_order_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order */
        get: operations["get_order_orders__order_guid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status */
        patch: operations["update_order_orders__order_guid__patch"];
        trace?: never;
    };
    "/orders/{order_guid}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create order row */
        post: operations["create_order_row_orders__order_guid__rows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order-rows/{order_row_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order row */
        patch: operations["update_order_row_order_rows__order_row_guid__patch"];
        trace?: never;
    };
    "/orders/{order_guid}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm order */
        post: operations["confirm_order_orders__order_guid__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_guid}/generate-commitments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate commitments for TO_ORDER rows */
        post: operations["generate_commitments_orders__order_guid__generate_commitments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_guid}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order audit log */
        get: operations["order_log_orders__order_guid__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commitments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commitments */
        get: operations["list_commitments_commitments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commitments/{commitment_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update commitment */
        patch: operations["update_commitment_commitments__commitment_guid__patch"];
        trace?: never;
    };
    "/pick-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pick notes */
        get: operations["list_pick_notes_pick_notes_get"];
        put?: never;
        /** Create pick note */
        post: operations["create_pick_note_pick_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pick-notes/{pick_note_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pick note */
        get: operations["get_pick_note_pick_notes__pick_note_guid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pick-notes/{pick_note_guid}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add pick note row */
        post: operations["add_pick_note_row_pick_notes__pick_note_guid__rows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_guid}/pick-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create pick note from order */
        post: operations["create_pick_note_from_order_orders__order_guid__pick_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List delivery notes */
        get: operations["list_delivery_notes_delivery_notes_get"];
        put?: never;
        /** Create delivery note */
        post: operations["create_delivery_note_delivery_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-notes/{delivery_note_guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get delivery note */
        get: operations["get_delivery_note_delivery_notes__delivery_note_guid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest mail */
        post: operations["ingest_mail_mails_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party_guid}/mails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List latest mails for party */
        get: operations["list_party_mails_parties__party_guid__mails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party_guid}/mails/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank mails for party (stub) */
        post: operations["rank_party_mails_parties__party_guid__mails_rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mails/{mail_guid}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract items from mail (stub) */
        post: operations["extract_mail_mails__mail_guid__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload attachment */
        post: operations["upload_attachment_attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachment_guid}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download attachment */
        get: operations["download_attachment_attachments__attachment_guid__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_type_code}/{entity_guid}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entity attachments */
        get: operations["list_entity_attachments_entities__entity_type_code___entity_guid__attachments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleAliasCreate */
        ArticleAliasCreate: {
            /** Alias */
            alias: string;
        };
        /** ArticleAliasOut */
        ArticleAliasOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Article Guid
             * Format: uuid
             */
            article_guid: string;
            /** Alias */
            alias: string;
        };
        /** ArticleCreate */
        ArticleCreate: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ArticleOut */
        ArticleOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Is Active */
            is_active: boolean;
        };
        /** AttachmentOut */
        AttachmentOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /** Entity Type Code */
            entity_type_code: string;
            /**
             * Entity Guid
             * Format: uuid
             */
            entity_guid: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Storage Path */
            storage_path: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By User Guid
             * Format: uuid
             */
            created_by_user_guid: string;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_attachment_attachments_post */
        Body_upload_attachment_attachments_post: {
            /** Entity Type Code */
            entity_type_code: string;
            /**
             * Entity Guid
             * Format: uuid
             */
            entity_guid: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CommitmentOut */
        CommitmentOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Order Row Guid
             * Format: uuid
             */
            order_row_guid: string;
            /**
             * Article Guid
             * Format: uuid
             */
            article_guid: string;
            /** Quantity */
            quantity: string;
            /** Status Code */
            status_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CommitmentUpdate */
        CommitmentUpdate: {
            /** Status Code */
            status_code?: string | null;
            /** Quantity */
            quantity?: number | string | null;
        };
        /** ContactCreate */
        ContactCreate: {
            /** Type Code */
            type_code: string;
            /** Content */
            content: string;
            /** Label */
            label?: string | null;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
        };
        /** ContactOut */
        ContactOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /** Type Code */
            type_code: string;
            /** Content */
            content: string;
            /** Normalized Content */
            normalized_content: string;
            /** Label */
            label: string | null;
            /**
             * Party Guid
             * Format: uuid
             */
            party_guid: string;
            /** Is Primary */
            is_primary: boolean;
        };
        /** ContactUpdate */
        ContactUpdate: {
            /** Content */
            content?: string | null;
            /** Label */
            label?: string | null;
            /** Is Primary */
            is_primary?: boolean | null;
        };
        /** DeliveryNoteCreate */
        DeliveryNoteCreate: {
            /**
             * Pick Note Guid
             * Format: uuid
             */
            pick_note_guid: string;
            /**
             * Customer Party Guid
             * Format: uuid
             */
            customer_party_guid: string;
            /**
             * Shipping Location Guid
             * Format: uuid
             */
            shipping_location_guid: string;
            /** Carrier Party Guid */
            carrier_party_guid?: string | null;
            /**
             * Delivery Date
             * Format: date
             */
            delivery_date: string;
        };
        /** DeliveryNoteOut */
        DeliveryNoteOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /**
             * Pick Note Guid
             * Format: uuid
             */
            pick_note_guid: string;
            /**
             * Customer Party Guid
             * Format: uuid
             */
            customer_party_guid: string;
            /**
             * Shipping Location Guid
             * Format: uuid
             */
            shipping_location_guid: string;
            /** Carrier Party Guid */
            carrier_party_guid: string | null;
            /**
             * Delivery Date
             * Format: date
             */
            delivery_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By User Guid
             * Format: uuid
             */
            created_by_user_guid: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationCreate */
        LocationCreate: {
            /** City */
            city?: string | null;
            /** Province */
            province?: string | null;
            /** Post Code */
            post_code?: string | null;
            /** Latitude */
            latitude?: number | string | null;
            /** Longitude */
            longitude?: number | string | null;
            /** Place Id */
            place_id?: string | null;
        };
        /** LocationOut */
        LocationOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /** City */
            city: string | null;
            /** Province */
            province: string | null;
            /** Post Code */
            post_code: string | null;
            /** Latitude */
            latitude: string | null;
            /** Longitude */
            longitude: string | null;
            /** Place Id */
            place_id: string | null;
        };
        /** MailCreate */
        MailCreate: {
            /** Message Id */
            message_id: string;
            /** Subject */
            subject: string;
            /** Sender */
            sender: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Body */
            body: string;
            /** Party Guid */
            party_guid?: string | null;
        };
        /** MailExtractionOut */
        MailExtractionOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Mail Guid
             * Format: uuid
             */
            mail_guid: string;
            /** Raw Item */
            raw_item: string;
            /** Quantity */
            quantity: string;
            /** Confidence */
            confidence: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By User Guid
             * Format: uuid
             */
            created_by_user_guid: string;
        };
        /** MailOut */
        MailOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /** Message Id */
            message_id: string;
            /** Subject */
            subject: string;
            /** Sender */
            sender: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Body */
            body: string;
            /** Party Guid */
            party_guid: string | null;
        };
        /** MailRankRequest */
        MailRankRequest: {
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /** OrderCreate */
        OrderCreate: {
            /**
             * Party Guid
             * Format: uuid
             */
            party_guid: string;
            /**
             * Order Date
             * Format: date
             */
            order_date: string;
            /** Payment Method Guid */
            payment_method_guid?: string | null;
            /** Billing Location Guid */
            billing_location_guid?: string | null;
            /** Shipping Location Guid */
            shipping_location_guid?: string | null;
        };
        /** OrderLogOut */
        OrderLogOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Order Guid
             * Format: uuid
             */
            order_guid: string;
            /**
             * User Guid
             * Format: uuid
             */
            user_guid: string;
            /** Action Code */
            action_code: string;
            /** Old Status Code */
            old_status_code: string | null;
            /** New Status Code */
            new_status_code: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderOut */
        OrderOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /**
             * Party Guid
             * Format: uuid
             */
            party_guid: string;
            /** Status Code */
            status_code: string;
            /**
             * Order Date
             * Format: date
             */
            order_date: string;
            /** Payment Method Guid */
            payment_method_guid: string | null;
            /** Billing Location Guid */
            billing_location_guid: string | null;
            /** Shipping Location Guid */
            shipping_location_guid: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By User Guid
             * Format: uuid
             */
            created_by_user_guid: string;
        };
        /** OrderRowCreate */
        OrderRowCreate: {
            /**
             * Article Guid
             * Format: uuid
             */
            article_guid: string;
            /** Quantity */
            quantity: number | string;
            /** Unit Price */
            unit_price: number | string;
            /** Vat Code */
            vat_code?: string | null;
            /**
             * Availability Status Code
             * @default UNKNOWN
             */
            availability_status_code: string;
        };
        /** OrderRowOut */
        OrderRowOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Order Guid
             * Format: uuid
             */
            order_guid: string;
            /**
             * Article Guid
             * Format: uuid
             */
            article_guid: string;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
            /** Vat Code */
            vat_code: string | null;
            /** Availability Status Code */
            availability_status_code: string;
        };
        /** OrderRowUpdate */
        OrderRowUpdate: {
            /** Quantity */
            quantity?: number | string | null;
            /** Unit Price */
            unit_price?: number | string | null;
            /** Availability Status Code */
            availability_status_code?: string | null;
        };
        /** OrderUpdate */
        OrderUpdate: {
            /** Status Code */
            status_code: string;
            /** Note */
            note?: string | null;
        };
        /** Page[ArticleOut] */
        Page_ArticleOut_: {
            /** Items */
            items: components["schemas"]["ArticleOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[CommitmentOut] */
        Page_CommitmentOut_: {
            /** Items */
            items: components["schemas"]["CommitmentOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[DeliveryNoteOut] */
        Page_DeliveryNoteOut_: {
            /** Items */
            items: components["schemas"]["DeliveryNoteOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[OrderOut] */
        Page_OrderOut_: {
            /** Items */
            items: components["schemas"]["OrderOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[PartyOut] */
        Page_PartyOut_: {
            /** Items */
            items: components["schemas"]["PartyOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[PickNoteOut] */
        Page_PickNoteOut_: {
            /** Items */
            items: components["schemas"]["PickNoteOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** PartyCreate */
        PartyCreate: {
            /** Description */
            description: string;
            /** Vat Number */
            vat_number?: string | null;
            /** Type Code */
            type_code: string;
        };
        /** PartyLocationCreate */
        PartyLocationCreate: {
            /**
             * Location Guid
             * Format: uuid
             */
            location_guid: string;
            /** Type Code */
            type_code: string;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
        };
        /** PartyLocationOut */
        PartyLocationOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Party Guid
             * Format: uuid
             */
            party_guid: string;
            /**
             * Location Guid
             * Format: uuid
             */
            location_guid: string;
            /** Type Code */
            type_code: string;
            /** Is Primary */
            is_primary: boolean;
        };
        /** PartyLocationUpdate */
        PartyLocationUpdate: {
            /** Type Code */
            type_code?: string | null;
            /** Is Primary */
            is_primary?: boolean | null;
        };
        /** PartyOut */
        PartyOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /** Description */
            description: string;
            /** Vat Number */
            vat_number: string | null;
            /** Type Code */
            type_code: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
        };
        /** PartyUpdate */
        PartyUpdate: {
            /** Description */
            description?: string | null;
            /** Vat Number */
            vat_number?: string | null;
            /** Type Code */
            type_code?: string | null;
        };
        /** PickNoteCreate */
        PickNoteCreate: {
            /**
             * Warehouse Guid
             * Format: uuid
             */
            warehouse_guid: string;
            /** Order Guid */
            order_guid?: string | null;
        };
        /** PickNoteOut */
        PickNoteOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /**
             * Warehouse Guid
             * Format: uuid
             */
            warehouse_guid: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By User Guid
             * Format: uuid
             */
            created_by_user_guid: string;
        };
        /** PickNoteRowCreate */
        PickNoteRowCreate: {
            /**
             * Article Guid
             * Format: uuid
             */
            article_guid: string;
            /** Quantity */
            quantity: number | string;
            /** Source Type Code */
            source_type_code: string;
            /** Source Guid */
            source_guid?: string | null;
        };
        /** PickNoteRowOut */
        PickNoteRowOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Pick Note Guid
             * Format: uuid
             */
            pick_note_guid: string;
            /**
             * Article Guid
             * Format: uuid
             */
            article_guid: string;
            /** Quantity */
            quantity: string;
            /** Source Type Code */
            source_type_code: string;
            /** Source Guid */
            source_guid: string | null;
        };
        /** RankedMail */
        RankedMail: {
            /**
             * Mail Guid
             * Format: uuid
             */
            mail_guid: string;
            /** Score */
            score: string;
            /** Subject */
            subject: string;
            /** Sender */
            sender: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Role Code */
            role_code: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarehouseCreate */
        WarehouseCreate: {
            /** Description */
            description: string;
            /** Location Guid */
            location_guid?: string | null;
        };
        /** WarehouseOut */
        WarehouseOut: {
            /**
             * Guid
             * Format: uuid
             */
            guid: string;
            /**
             * Master Data Guid
             * Format: uuid
             */
            master_data_guid: string;
            /** Description */
            description: string;
            /** Location Guid */
            location_guid: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_parties_parties_get: {
        parameters: {
            query?: {
                type_code?: string | null;
                search?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PartyOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_party_parties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_party_parties__party_guid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_party_parties__party_guid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_party_parties__party_guid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts_parties__party_guid__contacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_parties__party_guid__contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_contacts__contact_guid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_contacts__contact_guid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_location_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_location_locations__location_guid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_party_locations_parties__party_guid__locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyLocationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_party_location_parties__party_guid__locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyLocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyLocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_party_location_party_locations__party_location_guid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_location_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_party_location_party_locations__party_location_guid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_location_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyLocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyLocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_articles_get: {
        parameters: {
            query?: {
                search?: string | null;
                starts_with?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ArticleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aliases_articles__article_guid__aliases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleAliasOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_alias_articles__article_guid__aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleAliasCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleAliasOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_warehouses_warehouses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"][];
                };
            };
        };
    };
    create_warehouse_warehouses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_orders_get: {
        parameters: {
            query?: {
                party_guid?: string | null;
                status_code?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrderOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_orders__order_guid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_orders__order_guid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_row_orders__order_guid__rows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_row_order_rows__order_row_guid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_row_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_order_orders__order_guid__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_commitments_orders__order_guid__generate_commitments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    order_log_orders__order_guid__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commitments_commitments_get: {
        parameters: {
            query?: {
                party_guid?: string | null;
                status_code?: string | null;
                article_guid?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CommitmentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_commitment_commitments__commitment_guid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commitment_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pick_notes_pick_notes_get: {
        parameters: {
            query?: {
                warehouse_guid?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PickNoteOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pick_note_pick_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pick_note_pick_notes__pick_note_guid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pick_note_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_pick_note_row_pick_notes__pick_note_guid__rows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pick_note_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickNoteRowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickNoteRowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pick_note_from_order_orders__order_guid__pick_notes_post: {
        parameters: {
            query: {
                warehouse_guid: string;
            };
            header?: never;
            path: {
                order_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_delivery_notes_delivery_notes_get: {
        parameters: {
            query?: {
                customer_party_guid?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeliveryNoteOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_delivery_note_delivery_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_delivery_note_delivery_notes__delivery_note_guid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_note_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_mail_mails_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_party_mails_parties__party_guid__mails_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_party_mails_parties__party_guid__mails_rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_guid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailRankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankedMail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_mail_mails__mail_guid__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mail_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailExtractionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_attachment_attachments__attachment_guid__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entity_attachments_entities__entity_type_code___entity_guid__attachments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type_code: string;
                entity_guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
